local _, Data, env, db, name = CPAPI.LinkEnv(...);
---------------------------------------------------------------
LibStub('RelaTable')(name, env);
---------------------------------------------------------------
local MODID_EXTEND = {'SHIFT', 'CTRL', 'ALT', 'CTRL-SHIFT', 'ALT-SHIFT', 'ALT-CTRL'};
local BLUE = GenerateClosure(ColorMixin.WrapTextInColorCode, BLUE_FONT_COLOR)
---------------------------------------------------------------
-- Add variables to config
---------------------------------------------------------------
env.Variables = {
	_(BINDING_HEADER_TARGETING, BINDING_HEADER_TARGETING, 100);
	lazyLoadingEnable = _{Data.Bool(true);
		name = 'Enable Lazy Loading';
		desc = 'Activate targeting components only while their bindings are in use.';
		note = 'Automatically disabled if an inactive component is clicked from a macro.';
		advd = true;
	};
	unitHotkeyTokens = _{Data.String('[group:party] party1-4, player, party1-4pet, boss1-8, arena1-5 [group:raid] raid1-40, boss1-8 [] player');
		name = 'Unit Pool';
		desc = 'Units to watch, as lists of unit tokens selected by macro conditions. Use [] for the unconditional fallback.';
		note = 'E.g. '..BLUE('[group:party] party1-4, player [] player')..' watches your party while grouped, otherwise only yourself.';
		advd = true;
	};
	--------------------------------------------------------------------------------------------------------
	_('Target Ring', BINDING_HEADER_TARGETING);
	--------------------------------------------------------------------------------------------------------
	targetRingPrimaryStick = _{Data.Select(DEFAULT, DEFAULT, 'Movement', 'Camera', 'Gyro');
		name = 'Primary Stick';
		desc = 'Stick to use for this ring. Default follows the radial menu primary stick.';
		advd = true;
	};
	targetRingClassColor = _{Data.Bool(true);
		name = 'Class Colored Health';
		desc = 'Color the health bars in the target ring by class.';
	};
	targetRingPressAndHold = _{Data.Bool(true);
		name = 'Press and Hold';
		desc = 'Use press and hold to navigate and use rings. Press, point, release.';
		note = 'When disabled, you will need to press the accept button to confirm a selection.';
	};
	targetRingAcceptButton = _{Data.Button('PAD1');
		name = 'Accept Button';
		desc = 'Button used to confirm a selected item from a ring.';
		deps = { targetRingPressAndHold = false };
	};
	--------------------------------------------------------------------------------------------------------
	_('Raid Cursor', BINDING_HEADER_TARGETING);
	--------------------------------------------------------------------------------------------------------
	raidCursorScale = _{Data.Number(1, 0.1);
		name = 'Scale';
		desc = 'Scale of the cursor.';
	};
	raidCursorMode = _{Data.Map(1, {'Redirect', FOCUS, TARGET}),
		name = 'Targeting Mode';
		desc = 'Change how the raid cursor acquires a target. Redirect and focus modes will reroute appropriate spells without changing your target.';
		note = 'Basic redirect cannot route macros or ambiguous spells. Use target mode or focus mode with [@focus] macros to control behavior.';
	};
	raidCursorModifier = _{Data.Select('<none>', '<none>', unpack(MODID_EXTEND));
		name = 'Modifier';
		desc = 'Which modifier to use with the movement buttons to move the cursor.';
		note = 'The bindings underlying the button combinations will be unavailable while the cursor is in use.\n\nModifier can also be configured on a per button basis.';
	};
	raidCursorUp = _{Data.Button('PADDUP', true);
		name = 'Move Up';
		desc = 'Button to move the cursor up.';
		deps = { raidCursorModifier = '<none>' };
		advd = true;
	};
	raidCursorDown = _{Data.Button('PADDDOWN', true);
		name = 'Move Down';
		desc = 'Button to move the cursor down.';
		deps = { raidCursorModifier = '<none>' };
		advd = true;
	};
	raidCursorLeft = _{Data.Button('PADDLEFT', true);
		name = 'Move Left';
		desc = 'Button to move the cursor left.';
		deps = { raidCursorModifier = '<none>' };
		advd = true;
	};
	raidCursorRight = _{Data.Button('PADDRIGHT', true);
		name = 'Move Right';
		desc = 'Button to move the cursor right.';
		deps = { raidCursorModifier = '<none>' };
		advd = true;
	};
	raidCursorFilter = _{Data.String(nil);
		name = 'Filter Condition';
		desc = 'Filter condition to find raid cursor frames, as a boolean expression in Lua.';
		note = BLUE'node' .. ' is the current frame under scrutinization.\n'
			.. BLUE'unit' .. ' is the current unit ID for the frame.';
		advd = true;
	};
	raidCursorPriorityOverride = _{Data.Bool(false);
		name = 'Priority Override';
		desc = 'Prioritize raid cursor bindings over other override bindings.';
		advd = true;
	};
	raidCursorWrapDisable = _{Data.Bool(false);
		name = 'Disable Wrapping';
		desc = 'Prevent the cursor from wrapping when navigating.';
		advd = true;
	};
	raidCursorPortraitShow = _{Data.Bool(true);
		name = 'Show Portrait';
		desc = 'Show portrait for the current unit, with health percentage and applicable spell casts.';
		advd = true;
	};
	raidCursorPointerAnimation = _{Data.Bool(true);
		name = 'Enable Animation';
		desc = 'Pointer arrow rotates in the direction of travel, and portraits scale up and down on movement.';
		advd = true;
	};
	raidCursorPointerSize = _{Data.Number(22, 2, true);
		name = 'Pointer Size';
		desc = 'Size of pointer arrow, in pixels.';
		advd = true;
	};
	raidCursorPointerOffset = _{Data.Number(-2, 1);
		name = 'Pointer Offset';
		desc = 'Offset of pointer arrow, from the selected node center, in pixels.';
		advd = true;
	};
	raidCursorTravelTime = _{Data.Range(4, 1, 1, 10);
		name = 'Travel Time';
		desc = 'How long the cursor should take to transition from one node to another.';
		note = 'Higher is slower.';
		advd = true;
	};
	--------------------------------------------------------------------------------------------------------
	_('Unit Hotkeys', BINDING_HEADER_TARGETING);
	--------------------------------------------------------------------------------------------------------
	unitHotkeyFocusMode = _{Data.Bool(false);
		name = 'Use Focus Mode';
		desc = 'Hotkeys control your focus target instead of your current target.';
	};
	unitHotkeyInstantMode = _{Data.Bool(true);
		name = 'Use Instant Mode';
		desc = 'Hotkeys activate their target immediately.';
	};
	unitHotkeyStaticMode = _{Data.Bool(false);
		name = 'Use Static Mode';
		desc = 'Hotkeys always target the same unit.';
	};
	unitHotkeyDefaultMode = _{Data.Bool(true);
		name = 'Default to '..BLUE(GetBindingName('TARGETSCANENEMY'));
		desc = 'Hotkeys use '..BLUE(GetBindingName('TARGETSCANENEMY'))..' when no target is selected.';
	};
	unitHotkeyNamePlates = _{Data.Bool(true);
		name = 'Show on Name Plates';
		desc = 'Hotkey prompts appear on applicable name plates.';
	};
	unitHotkeyGhostMode = _{Data.Bool(false);
		name = 'Always Show';
		desc = 'Hotkey prompts linger on unit frames after targeting.';
	};
	unitHotkeyGhostAlpha = _{Data.Number(0.5, 0.05, true);
		name = 'Inactive Opacity';
		desc = 'Opacity of inactive hotkey prompts on unit frames after targeting.';
	};
	unitHotkeySize = _{Data.Number((CPAPI.IsClassicEraVersion or CPAPI.IsAnniVersion) and 32 or 24, 1);
		name = 'Size';
		desc = 'Size of unit hotkeys, in pixels.';
	};
	unitHotkeyOffsetX = _{Data.Number(0, 1, true);
		name = 'Horizontal Offset';
		desc = 'Horizontal offset of the hotkey prompt position, in pixels.';
		advd = true;
	};
	unitHotkeyOffsetY = _{Data.Number(0, 1, true);
		name = 'Vertical Offset';
		desc = 'Vertical offset of the hotkey prompt position, in pixels.';
		advd = true;
	};
	unitHotkeyOffsetFL = _{Data.Number(10, 1, true);
		name = 'Frame Level Offset';
		desc = 'Frame level offset of the hotkey prompt, relative to the unit frame.';
		note = 'Higher values appear on top of lower values. Valid range 0-10000.';
		advd = true;
	};
	unitHotkeySet = _{Data.Select('Dynamic', 'Dynamic', 'Left', 'Right', 'Custom');
		name = 'Button Set';
		desc = 'Which button set to use for unit hotkeys.';
		note = 'Dynamic will use the button set that does not conflict with your '..BLUE'L[Target Unit Frames (Hold)]'..' binding.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyButton1 = _{Data.Button('PAD1');
		name = 'Combo Button 1';
		desc = 'Button to use for combo hotkey 1.';
		note = 'Requires '..BLUE'L[Button Set]'..' > '..BLUE'L[Custom]'..' to control each button individually.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyButton2 = _{Data.Button('PAD2');
		name = 'Combo Button 2';
		desc = 'Button to use for combo hotkey 2.';
		note = 'Requires '..BLUE'L[Button Set]'..' > '..BLUE'L[Custom]'..' to control each button individually.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyButton3 = _{Data.Button('PAD3');
		name = 'Combo Button 3';
		desc = 'Button to use for combo hotkey 3.';
		note = 'Requires '..BLUE'L[Button Set]'..' > '..BLUE'L[Custom]'..' to control each button individually.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyButton4 = _{Data.Button('PAD4');
		name = 'Combo Button 4';
		desc = 'Button to use for combo hotkey 4.';
		note = 'Requires '..BLUE'L[Button Set]'..' > '..BLUE'L[Custom]'..' to control each button individually.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyButton5 = _{Data.Button('PADDDOWN', true):Set('none', true);
		name = 'Combo Button 5';
		desc = 'Button to use for combo hotkey 5.';
		note = 'Requires '..BLUE'L[Button Set]'..' > '..BLUE'L[Custom]'..' to control each button individually.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyButton6 = _{Data.Button('PADDRIGHT', true):Set('none', true);
		name = 'Combo Button 6';
		desc = 'Button to use for combo hotkey 6.';
		note = 'Requires '..BLUE'L[Button Set]'..' > '..BLUE'L[Custom]'..' to control each button individually.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyButton7 = _{Data.Button('PADDLEFT', true):Set('none', true);
		name = 'Combo Button 7';
		desc = 'Button to use for combo hotkey 7.';
		note = 'Requires '..BLUE'L[Button Set]'..' > '..BLUE'L[Custom]'..' to control each button individually.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyButton8 = _{Data.Button('PADDUP', true):Set('none', true);
		name = 'Combo Button 8';
		desc = 'Button to use for combo hotkey 8.';
		note = 'Requires '..BLUE'L[Button Set]'..' > '..BLUE'L[Custom]'..' to control each button individually.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyColor1 = _{Data.Color('ffffffff');
		name = 'Combo Color 1';
		desc = 'Color tint for combo hotkey 1.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyColor2 = _{Data.Color('ffffffff');
		name = 'Combo Color 2';
		desc = 'Color tint for combo hotkey 2.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyColor3 = _{Data.Color('ffffffff');
		name = 'Combo Color 3';
		desc = 'Color tint for combo hotkey 3.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyColor4 = _{Data.Color('ffffffff');
		name = 'Combo Color 4';
		desc = 'Color tint for combo hotkey 4.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyColor5 = _{Data.Color('ffffffff');
		name = 'Combo Color 5';
		desc = 'Color tint for combo hotkey 5.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyColor6 = _{Data.Color('ffffffff');
		name = 'Combo Color 6';
		desc = 'Color tint for combo hotkey 6.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyColor7 = _{Data.Color('ffffffff');
		name = 'Combo Color 7';
		desc = 'Color tint for combo hotkey 7.';
		list = CONTROLS_LABEL;
		advd = true;
	};
	unitHotkeyColor8 = _{Data.Color('ffffffff');
		name = 'Combo Color 8';
		desc = 'Color tint for combo hotkey 8.';
		list = CONTROLS_LABEL;
		advd = true;
	};
};

ConsolePort:AddVariables(env.Variables)
